### ISSUE TITLE
GXDLMSTranslator using wrong getCiphering defenitions

### ISSUE THREAD

**Issue by i96751414** [Gurux/Gurux.DLMS.Python#14]
The below code is inconsistent and breaks `GXDLMSTranslator`.

Currently, `getCiphering` expects 2 arguments and does not return a value:

https://github.com/Gurux/Gurux.DLMS.Python/blob/213e909be75615f279a7b82edb84e485f9e7e21f/Gurux.DLMS.python/gurux_dlms/GXDLMSTranslator.py#L290-L302

However, `getCiphering` calls are being performed as shown below:

https://github.com/Gurux/Gurux.DLMS.Python/blob/213e909be75615f279a7b82edb84e485f9e7e21f/Gurux.DLMS.python/gurux_dlms/GXDLMSTranslator.py#L353
https://github.com/Gurux/Gurux.DLMS.Python/blob/213e909be75615f279a7b82edb84e485f9e7e21f/Gurux.DLMS.python/gurux_dlms/GXDLMSTranslator.py#L523
https://github.com/Gurux/Gurux.DLMS.Python/blob/213e909be75615f279a7b82edb84e485f9e7e21f/Gurux.DLMS.python/gurux_dlms/GXDLMSTranslator.py#L537
https://github.com/Gurux/Gurux.DLMS.Python/blob/213e909be75615f279a7b82edb84e485f9e7e21f/Gurux.DLMS.python/gurux_dlms/GXDLMSTranslator.py#L546

**Comment by gurux01** [comment]
This is fixed in version 1.0.50. Your name is added to credits.
