### ISSUE TITLE
integerToHex wrongly converting negative integers

### ISSUE THREAD

**Issue by i96751414** [Gurux/Gurux.DLMS.Python#15]
Already reported in http://www.gurux.fi/node/13723.

`integerToHex` method of `_GXCommon.py` is wrongly converting negative integers to hex. For instance, `-4` should be converted to `FC`, however it is converting it to `X4`. This is happening due to `str_ = hex(value)[2:]` line, as `hex(-4)` is `'-0x4'`.

https://github.com/Gurux/Gurux.DLMS.Python/blob/213e909be75615f279a7b82edb84e485f9e7e21f/Gurux.DLMS.python/gurux_dlms/internal/_GXCommon.py#L308-L313

A possible fix for this would be to implement something like https://gist.github.com/i96751414/b1ed2aef2cb9f602d03c305e22cb6e13

**Comment by gurux01** [comment]
This is fixed in version 1.0.50. Your name is added to credits.
