### ISSUE TITLE
dont we have to pass only the setting in this function ? 

### ISSUE THREAD

**Issue by jk-arm** [Gurux/Gurux.DLMS.Python#17]
https://github.com/Gurux/Gurux.DLMS.Python/blob/88cbe8e610a0178adee1526c5aa6d8990d74d373/Gurux.DLMS.python/gurux_dlms/GXDLMSTranslator.py#L353

**Comment by gurux01** [comment]
Force parameter is added because it helps decrypt messages. Without that, you need to set the authentication level to something else than None. This was causing misunderstandings with the users.
