### ISSUE TITLE
getCiphering function takes the settings.cipher and the function is trying to set the value settings.ciphering inside the function

### ISSUE THREAD

**Issue by jk-arm** [Gurux/Gurux.DLMS.Python#18]
def getCiphering(self, settings, force):
        if force or self.security != Security.NONE:
            c = GXCiphering(self.systemTitle)
            c.security = self.security
            c.systemTitle = self.systemTitle
            c.blockCipherKey = self.blockCipherKey
            c.authenticationKey = self.authenticationKey
            c.invocationCounter = self.invocationCounter
            c.dedicatedKey = self.dedicatedKey

exception starts here
--------------------------
            settings.sourceSystemTitle = self.serverSystemTitle
            settings.cipher = c
        else:
            settings.cipher = None

exception ends here
--------------------------

exception is happeneing because there is no settings here. only settings.cipher is passed to the functions.

https://github.com/Gurux/Gurux.DLMS.Python/blob/88cbe8e610a0178adee1526c5aa6d8990d74d373/Gurux.DLMS.python/gurux_dlms/GXDLMSTranslator.py#L353

**Comment by gurux01** [comment]
This is fixed in version 1.0.51. Your name is added to credits.
