### ISSUE TITLE
setUInt8 should not be capitalized

### ISSUE THREAD

**Issue by vascomedici** [Gurux/Gurux.DLMS.Python#2]
setUInt8 should not be capitalized here
https://github.com/Gurux/Gurux.DLMS.Python/blob/96ea2a3110091e606cc8b58442eb682469aa27b9/Gurux.DLMS.python/gurux_dlms/_GXAPDU.py#L142
and here
https://github.com/Gurux/Gurux.DLMS.Python/blob/96ea2a3110091e606cc8b58442eb682469aa27b9/Gurux.DLMS.python/gurux_dlms/_GXAPDU.py#L144

**Comment by gurux01** [comment]
Thank you from this info. This is fixed in version 1.0.18. Your name is added to credits.
