### ISSUE TITLE
Class CGXDLMSClient

### ISSUE THREAD

**Issue by Jonamaita** [Gurux/Gurux.DLMS.Python#31]
Hello !!! 

Try using the CGXDLMSClient class  which is described in the example of `README.md.`  But that class no exist.

```shell
>>>from gurux_dlms import *
>>>dir(CGXDLMSClient)     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'CGXDLMSClient' is not defined
```

Is the 'README.md' outdated?.

Thank you!!.

**Comment by gurux-kurumi** [comment]
Hi,

There is a typo. It should be GXDLMSClient and not CGXDLMSClient. This will be updated today.

BR,
Mikko
