### ISSUE TITLE
Possible problem in GXDLMS.py

### ISSUE THREAD

**Issue by zon7** [Gurux/Gurux.DLMS.Python#33]
On line 996, there is an operation that seems to be wrong.
`compleate = not (len(buff) - buff.position) < value`

I think it should be
`compleate = not (len(buff) - buff.position < value)`

**Comment by gurux-kurumi** [comment]
Hi,

I verify this and the result is the same in both ways. The round brackets are not needed at all.

You can try this by yourself if you change the value from 7 to 8. Value is the expected length.
value = 7
buff = GXByteBuffer("7E A0 07 03 21 93 0F 01 7E")
buff.position = 2
compleate = not (len(buff) - buff.position) < value
compleate = not (len(buff) - buff.position < value)
compleate = not len(buff) - buff.position < value

BR,
Mikko

**Comment by zon7** [comment]
Maybe result is the same, but I think the line is meant to determine if the tcp data is complete, and it's complete if the buffer length is at least the value size. In the other two options you are doing boolean vs number and that's incorrect.
I mean:
compleate = not (len(buff) - buff.position) < value **->** boolean < number **WRONG**
compleate = not (len(buff) - buff.position < value) **->** not(number-number< number) **CORRECT**
compleate = not len(buff) - buff.position < value **->** bolean - number < number **WRONG**

**Comment by gurux-kurumi** [comment]
Hi,

You can think it like this:
Boolean value is False:
compleate = not ((len(buff) - buff.position) < value)
OR expecting that boolean is True:
compleate = len(buff) - buff.position > value

In presudo code:
compleate = (len(buff) - buff.position) < value) == False

Not is used here to check that result is false.

BR,
Mikko
