### ISSUE TITLE
broadcast bug

### ISSUE THREAD

**Issue by diegofontana** [Gurux/Gurux.DLMS.Python#35]
the following address check should have a mask

https://github.com/Gurux/Gurux.DLMS.Python/blob/ce36ef28aeaa68bc78731b39ba470f02de14d1c0/Gurux.DLMS.python/gurux_dlms/GXDLMS.py#L968

like in .net
https://github.com/Gurux/Gurux.DLMS.Net/blob/a2b5d5d27c99a5ff12384053ac92e958a72ec02d/Development/GXDLMS.cs#L2782

**Comment by diegofontana** [comment]
pull request was made for this bug

**Comment by gurux01** [comment]
This is updated and your name is added for credits.
