### ISSUE TITLE
Repeated Timeout Exception

### ISSUE THREAD

**Issue by pylenin** [Gurux/Gurux.DLMS.Python#5]
I am trying to use the Gurux.DLMS.Client.Example.python to connect to one of my meters. I am passing in the host, port, authentication, client address and server address. 

Everytime I run 
```
python main.py -h <host> -p <port> -P <passsword> -c 1 -s 1 -a low
```
I get the following result.
![Capture](https://user-images.githubusercontent.com/44732615/66831650-7b853a00-ef58-11e9-8047-91a6b63d9cf7.PNG)

What is the reason behind this?

**Comment by gurux01** [comment]
Hi,

If you have questions ask them on Gurux Forum.  
https://www.gurux.fi/forum
